### PR TITLE
Design input fields and buttons - Forgot Password Page

### PR DESCRIPTION
**Pull request by Chrysotile**

### CODE REVIEW

**Review by ChibiKev — CHANGES_REQUESTED** [review]
Can you remove the __pycache__ folders that were generated when running the backend.
Also add it into the .gitignore so it doesn't get pushed again. Make sure it doesn't push anything with that folder anymore.

**Review by ChibiKev — CHANGES_REQUESTED** [review]
You're missing states on ForgotPassword.js.
You're able to change states right now, but if you didn't initialize your states, how are you suppose to change them

**Review by ChibiKev — APPROVED** [review]
Good work.

**Review by albfelix31 — APPROVED** [review]

**Review by OzunaEddie — APPROVED** [review]
Looks good to me!

**Pull request merged**
