### PR TITLE
fixed css of access pages containers 

### PR DESCRIPTION
**Pull request by albfelix31**
Before, the containers in the access pages would shrink size when changing the screen page. Now, their size stays static all throughout.

### CODE REVIEW

**Comment by ChibiKev** [comment]
Do you mind taking a picture of your before and after?
This is what shows up for me. Before is current, after is your pull request. It cuts off part of the container since it's static.
Before
image
After
image

**Comment by albfelix31** [comment]
**Before:**
Screen Shot 2020-11-10 at 1 41 43 AM
Screen Shot 2020-11-10 at 1 41 35 AM
Screen Shot 2020-11-10 at 1 41 26 AM

**After:**
Screen Shot 2020-11-10 at 1 42 46 AM
Screen Shot 2020-11-10 at 1 42 57 AM

**Comment by albfelix31** [comment]
Try changing the vertical height of the screen before and after

**Comment by ChibiKev** [comment]
The thing is, it's technically impossible for the height to ever be that small.
Not tablets, phones, or any small screen size would ever have that type of height. They mainly have an issue with width.

**Comment by albfelix31** [comment]
Yes, it is impossible for phones/tablets/other small screens to have that height, but computers/laptops can have this height. Basically what I'm seeing is that the height of the components of our other pages stays static all throughout when you decrease the size of the screen, but it seems like the container of the forms for the access pages changes according to the height of the screen so that you can still see the fields. In these screenshots, it even cuts off in the middle of the footnote.
Screen Shot 2020-11-10 at 1 41 43 AM
Screen Shot 2020-11-10 at 1 41 35 AM

**Comment by albfelix31** [comment]
You also don't have to even make it that small to see that the size of the containers is being adjusted based on the height of the screen. If you look at other pages like Facebook for example, this doesn't happen - the height of the containers stays the same. Since users can just scroll through the page, the container height doesn't need to be adjusted based on screen height.

**Comment by ChibiKev** [comment]
Yeah. I see it. That fixes the problem with the height. But a new problem arises with the width. Some of the text gets cut off.
image

**Comment by albfelix31** [comment]
@ChibiKev fixed.
Screen Shot 2020-11-11 at 2 52 58 PM

**Review by ChibiKev — APPROVED** [review]
Good Work.

**Pull request merged**
