### PR TITLE
Frontend setup kc

### PR DESCRIPTION
**Pull request by ChibiKev**
Finished The Epic Regarding Frontend Setup.
@albfelix31 can now start working on the navbar.
@Chrysotile could also start working on the login/forgot password pages.

### CODE REVIEW

**Review by OzunaEddie — APPROVED** [review]
Great job!

**Comment by OzunaEddie** [comment]
great job!

**Review by Chrysotile — APPROVED** [review]
Great job!

**Review by albfelix31 — APPROVED** [review]
LGTM!

**Pull request merged**
