### PR TITLE
Database design

### PR DESCRIPTION
**Pull request by OzunaEddie**

### CODE REVIEW

**Review by ChibiKev — DISMISSED** [review]
Good Work. 
Although I have a question regarding the price. 
Sometimes there is no price. Let's say, they are not looking for money, but instead looking for another textbook as a price (only looking to trade and not sell. Or both options, sell and trade). Then would price still be an integer? If that is not the case, then should it be a Double instead of an INT (for example, 10.99)

**Comment by OzunaEddie** [comment]
> Good Work.
> Although I have a question regarding the price.
> Sometimes there is no price. Let's say, they are not looking for money, but instead looking for another textbook as a price (only looking to trade and not sell. Or both options, sell and trade). Then would price still be an integer? If that is not the case, then should it be a Double instead of an INT (for example, 10.99)

We can instead change the price datatype to varchar so that way we can insert strings. So it can be anything

**Review by ChibiKev — APPROVED** [review]
Good Work.
I've also changed the Transaction Table as well to match with the Currently Listed.

**Comment by OzunaEddie** [comment]
> Good Work.
> I've also changed the Transaction Table as well to match with the Currently Listed.

Good work on spotting that. I overlooked that. Good job!

**Review by Chrysotile — APPROVED** [review]
Looks good!

**Pull request merged**
