### PR TITLE
Navbar Design

### PR DESCRIPTION
**Pull request by albfelix31**
Formatted design of navbar so that it is center-aligned, selected tab is underlined red, and it is responsive across all platforms.

### CODE REVIEW

**Comment by ChibiKev** [comment]
I've just changed your vanilla bootstrap code into React Bootstrap. Could you reapply the css into it?

**Review by OzunaEddie — CHANGES_REQUESTED** [review]
need to center the navbar links

**Review by OzunaEddie — DISMISSED** [review]
Looks Good To me!

**Review by OzunaEddie — DISMISSED** [review]
Looks good to me!

**Comment by ChibiKev** [comment]
I fixed the warning messages that showed up on the console by: 
- In Navbar2, they don't allow comma in line 31-33. So instead I just kept it as NavLink since  it's basically the same thing as Link.
- Also in Navbar2, I added a default case for the switch since it was giving warnings in the console without it. The default case that I added was null since we would not want it to render anything if the case was not found. For more information, refer to [Here](https://reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering)
- In index.js, I got rid of React.StrictMode since it was giving warnings with BrowserRouter. For more information, [Here]( https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage)

I refracted some of the code by:
- Fixing the spacing of the code, the default spacing is 2, not 4. So to keep it consistent, I modified Navbar2.css
- I commented on Navbar2.css, it helps better understand what each of the css is doing and why.
- I also shortened the code. I noticed how there was an id attribute of basic-navbar-nav, it margin-right 30%. Then in the bottom, there was 2 classes that margin left 20% the same thing. It was basically going right 30% and then left 20% so I made it to just go right 10% instead.

**Review by OzunaEddie — APPROVED** [review]

**Review by ChibiKev — APPROVED** [review]

**Review by Chrysotile — APPROVED** [review]

**Pull request merged**
